### PR TITLE
Add header shadow and enhance result templates

### PR DESCRIPTION
**Pull request by Glignos**
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/334
* Addresses https://github.com/inveniosoftware/invenio-app-rdm/issues/333
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/327

### CODE REVIEW

**Comment by Glignos** [comment]
Screenshot 2020-10-22 at 14 55 55

**Comment by Glignos** [comment]
Screenshot 2020-10-22 at 15 03 53

**Comment by Glignos** [comment]
Screenshot 2020-10-27 at 15 03 00

**Comment by lnielsen** [comment]
For the nested facet can we do something similar to open data:
Screenshot 2020-10-27 at 16 07 56

I would merge this, and do the facet change i new PR.

**Comment by lnielsen** [comment]
Also, number 5 in #333 is not fixed (judging from the screenshot), hence it shoudl only be addressing the issue, not closing it

**Comment by Glignos** [comment]
@lnielsen fixed the Issue tag to addresses we can move towards merging this and I will create 2 new PR's regarding the 2 remaining issues (localized date and nested facets)

**Pull request merged**
