### PR TITLE
Add GND Icon

### PR DESCRIPTION
**Pull request by dfdan**
:heart: Thank you for your contribution!

### Description

We needed GND Icons for creatibutors, so I've added them here.
I can't find any tests/docs for the existing icons, so I'm hoping this is okay as-is. 

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [x] I've added relevant test cases.
- [x] I've added relevant documentation.
- [X] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [X] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [X] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [X] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [x] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Comment by lnielsen** [comment]
@dfdan Do you have a screenshot of how it looks like?

**Comment by lnielsen** [comment]
@jennur Can I ask you for a review

**Review by jennur — COMMENTED** [review]
Code looks fine to me, but please add screenshots :)

**Comment by dfdan** [comment]
Happy to - 

Image

PastedGraphic-1

I couldn't find an issue for the text-icon spacing in search view - but I've used all the same classes so any fix should work for them both so it felt out of scope for this quantum of work. I'm happy to take a look at this if nobody else is looking at search page stuff currently? 

Note that as the code seems to want where a creatibutor has an Orcid and GND you just get 1 identifier icon - that applies to me in the screenshots above. I may open a separate issue debating this logic...

**Review by jennur — APPROVED** [review]
Thanks! Yes, I agree these issues can be solved in a different task.

**Comment by dfdan** [comment]
A couple of updates:

* awaiting copyright clearance for the GND icon.
* react-invenio-deposit#481 adds the GND icon to the deposit form entries.
* the above PR requires icon from this PR so version dependency needs checking.

**Comment by dfdan** [comment]
GND icon confimed to be in creative commons thus we may include:
https://commons.wikimedia.org/wiki/File:Logo_Gemeinsame_Normdatei_(GND).svg

**Pull request merged**
