### PR TITLE
sidebar: display 'Sizes' properly [+]

### PR DESCRIPTION
**Pull request by fenekku**
- fix to display Sizes (wasn't displaying in v12)
- simplify formats as well

I will backport this to maint-v12.x when merged.

### CODE REVIEW

**Review by max-moser — COMMENTED** [review]
the `list_formats` seems to have been a basically equivalent re-implementation of `", ".join()`, that looks fine
the `list_string_values` macro is [this one here?](<https://github.com/inveniosoftware/invenio-app-rdm/blob/maint-v12.0.x/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/macros/detail.html#L34>) – how did it work before?
it looks like the macro wants two arguments, but was only supplied one?

**Comment by max-moser** [comment]
the logic changes look simple enough, but i have no idea about what it looked like before – could i ask you for before/after screenshots?

**Comment by fenekku** [comment]
Yes no problem!

**before**
before_sizes

**after**
after_sizes

It's indeed because the list_string_values wasn't given the additional parameter, but in this scenario that whole logic was unnecessary as far as I can tell.

**Comment by max-moser** [comment]
thanks!
looks like it previously was just plain broken :skull: 
much better now!

**Review by max-moser — APPROVED** [review]

**Pull request merged**
