### PR TITLE
 i18n: add SV translations

### PR DESCRIPTION
**Pull request by Samk13**
:heart: Thank you for your contribution!

### Description

Add Swedish translation support for invenio-app-rdm

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [x] I've added relevant test cases.
- [x] I've added relevant documentation.
- [x] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [x] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [x] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [x] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [x] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Review by zzacharo — APPROVED** [review]
@mb-wali can you also have a look?

**Comment by mb-wali** [comment]
@Samk13 - thank you for the contribution, I would have to put this on the i18n board for now, and wait until we have finished with the changes to the strings. I would see that this also gets pushed to the transifex.

**Comment by Samk13** [comment]
Thank you @mb-wali  When you are done with the strings changes, please ping me on discord if there is any action required from my side so we can have these changes shipped with v10 hopefully.

**Comment by ntarocco** [comment]
The CI workflow had an issue with installing dependencies, I have restarted it. Sorry for the incovenience.

**Comment by mb-wali** [comment]
closed with https://github.com/inveniosoftware/invenio-app-rdm/pull/1930

**Comment by Samk13** [comment]
Closing reason: 
https://discord.com/channels/692989811736182844/704625518552547329/1029661777690120252

**Pull request closed without merging**
