### PR TITLE
ui: fix footer to stick to bottom

### LINKED ISSUE #384: ux: footer space
The footer should be at the end of the browser and also spaced with the "jump" button

Screenshot 2020-11-10 at 16 17 08

Screenshot 2020-11-10 at 16 16 57

Screenshot 2020-11-10 at 16 16 40

Screenshot 2020-11-10 at 16 18 28

### PR DESCRIPTION
**Pull request by slint**
* Closes #384.

### CODE REVIEW

**Comment by slint** [comment]
image

**Comment by slint** [comment]
"Results per page" is still a bit low: 
image

**Comment by zzacharo** [comment]
@slint check also the pagination in the search page if you fix the results per page... See how is displayed now:
Screenshot 2020-11-11 at 09 58 58

**Review by zzacharo — APPROVED** [review]

**Comment by slint** [comment]
Also fixed now with some `padding-top`:

image

**Pull request merged**
