### PR TITLE
search: signal if more than 3 authors

### LINKED ISSUE #1873: Truncated creator name list in search results
## Is your feature request related to a problem? Please describe.
The search results truncate to the first three creators. There is no indication that there are other creators on the record. This is particularly confusing when you have a record with four creators, since it looks like data is missing.

## Describe the solution you'd like
An indication that other creators are present but not listed. The simplest would be "..." linked to the record landing page

## Describe alternatives you've considered
Showing more creators and wrapping is possible but tricky on small screens. "Et al." is the traditional approach, but not sure whether we have to think about translation.

## Additional context
Mockup:
Screen Shot 2022-09-14 at 9 49 15 AM

### PR DESCRIPTION
**Pull request by fenekku**
- closes #1873

**Screenshot (most recent)**

search_and_other_s_v2

### CODE REVIEW

**Comment by tmorrell** [comment]
Awesome! Could we get a screenshot? I'm nervous that "and other(s)" might get a bit long

**Comment by fenekku** [comment]
Oups sorry I took the screenshot but forgot to add it and add some discussion here :sweat_smile: .

So I tried with `...` too and it didn't stand out clearly enough (a bit too small and squeezed) - felt like a rendering artifact. I tried `more` and `et al.`, but `more` wasn't quite the right word in the end and `et al.` is typically strictly for "and others" plural, there is the translation thing your mentioned, and perhaps it's a bit too high brow.

This morning I just thought about a more nuanced version, which might be better, which is the "counted others". Something like:

for 1 more author

image

for more than 1 more author:

image

I saw translation mechanisms that should allow this. I will change it and wait for more feedback.

**Comment by tmorrell** [comment]
That looks really nice! One thought-could you link it to the record landing page? Since the other authors are linked it would be nice if the "n others" led you to where you see who they are.

**Comment by fenekku** [comment]
> That looks really nice! One thought-could you link it to the record landing page? Since the other authors are linked it would be nice if the "n others" led you to where you see who they are.

Yes, that makes sense!

**Comment by fenekku** [comment]
Done :santa:

**Review by jennur — APPROVED** [review]
LGTM! Thanks for fixing this!

**Pull request merged**
