### PR TITLE
facets: reduce negative space and align facets with results header

### PR DESCRIPTION
**Pull request by NRodriguezcuellar**
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1702

Screenshot from 2022-06-10 10-48-52
Screenshot from 2022-06-08 09-51-44
Screenshot from 2022-06-08 09-51-33

### CODE REVIEW

**Comment by jennur** [comment]
@kpsherva I agree. The spacing in this screenshot looks better I think. 
image
Maybe the column-widths are off in the other pages? The sidebar is meant to follow the layout like here https://github.com/inveniosoftware/invenio-search-ui/blob/master/invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js#L135 with 4-column with for the sidebar and 12 on the main content (on desktop).

**Comment by NRodriguezcuellar** [comment]
> @kpsherva I agree. The spacing in this screenshot looks better I think. image ~Maybe the column-widths are off in the other pages? The sidebar is meant to follow the layout like here https://github.com/inveniosoftware/invenio-search-ui/blob/master/invenio_search_ui/assets/semantic-ui/js/invenio_search_ui/components/SearchApp.js#L135 with 4-column with for the sidebar and 12 on the main content (on desktop).~ Edit: It looks like it is a big-screen issue?

it is because the cards have a fixed widths, on big screens that means there is more space left

**Comment by jennur** [comment]
Regarding the latest updated screenshot, I don't think the spacing should be affected in the sidebar for tablet/mobile. It looks a bit cramped now in the slide-in-version of the sidebar. It's only the widest screen that has too much spacing, no?

**Comment by NRodriguezcuellar** [comment]
> Regarding the latest updated screenshot, I don't think the spacing should be affected in the sidebar for tablet/mobile. It looks a bit cramped now in the slide-in-version of the sidebar. It's only the widest screen that has too much spacing, no?

i updated the picture, better like this?

**Comment by kpsherva** [comment]
> i updated the picture, better like this?
definitely better, but I think you did it with CSS while you could change the column width in the grid of the page? Or there is a PR missing?

**Review by jennur — APPROVED** [review]

**Comment by jennur** [comment]
I just noticed, after approving, that on the widest screen, the facets are not aligned with the header anymore. Maybe it should be solved by increasing the width of the right column on the biggest screen like Karolina suggested? There is a setting for the widest screen in SUI `widescreen` https://react.semantic-ui.com/collections/grid/ Although the content of the right column will get very wide in that case. Idk what we prefer, more space between the columns and more narrow content,  or less space and wider content.

**Review by kpsherva — APPROVED** [review]

**Pull request merged**
