### PR TITLE
landing_page: add block user option

### PR DESCRIPTION
**Pull request by 0einstein0**
closes https://github.com/zenodo/zenodo-rdm/issues/952

### CODE REVIEW

**Comment by yashlamba** [comment]
Closes https://github.com/zenodo/zenodo-rdm/issues/952

**Comment by carlinmack** [comment]
@yashlamba can you add screenshot/s

**Review by ntarocco — APPROVED** [review]
Code wise, LGTM, even if I am very allergic to React **hooks**.
It would be nice to see a screenshot indeed.
Does the block button already exist, and this is duplicating it?

**Comment by yashlamba** [comment]
Screenshot 2024-10-07 at 15 17 47
Screenshot 2024-10-07 at 15 18 29

**Pull request merged**
