### PR TITLE
search-ui: grammatical pedantry

### PR DESCRIPTION
**Pull request by dfdan**
Quick grammar fix - should be "1 more version exists" in the singular / "n more versions exist" in the plural

### CODE REVIEW

**Comment by dfdan** [comment]
I give up, why does that fail? :(

**Comment by fenekku** [comment]
I think the linter wants "this" to be on the following line because the line is too long now :/ .

**Review by fenekku — APPROVED** [review]
Apart from the silly linting, it's fine by me.

**Comment by dfdan** [comment]
Closing as with comment on #2188 as it deals with i18n side of this issue.

**Pull request closed without merging**
